kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: my-tutorial
  namespace: my-smcp
spec:
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
---
kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: customer-gateway
  namespace: my-tutorial
spec:
  servers:
    - hosts:
        - my-tutorial-my-smcp.apps.cluster-e7a6.e7a6.sandbox1459.opentlc.com
      port:
        name: http
        number: 80
        protocol: HTTP
  selector:
    istio: ingressgateway
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: customer
  namespace: my-tutorial
spec:
  hosts:
    - customer
    - recommendation
    - my-tutorial-my-smcp.apps.cluster-e7a6.e7a6.sandbox1459.opentlc.com
  gateways:
    - customer-gateway
  http:
    - match:
        - uri:
            exact: /customer
      rewrite:
        uri: /
      route:
        - destination:
            host: customer
            port:
              number: 8080
    - match:
        - uri:
            exact: /recommendation
      rewrite:
        uri: /
      route:
        - destination:
            host: recommendation
            subset: v1
          weight: 80
        - destination:
            host: recommendation
            subset: v2
          weight: 20
---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: recommendation
  namespace: my-tutorial
spec:
  host: recommendation
  subsets:
    - labels:
        version: v1
      name: v1
    - labels:
        version: v2
      name: v2
    - labels:
        version: v3
      name: v3
