kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: recommendation
  namespace: my-tutorial
spec:
  hosts:
    - recommendation
  http:
    - match:
        - headers:
            user-location:
              exact: Boston
      route:
        - destination:
            host: recommendation
            subset: v2
    - route:
        - destination:
            host: recommendation
            subset: v1
